
name: Update Publications from ORCID
on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:
jobs:
  update-pubs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Update publications
        env:
          ORCID_TOKEN: ${{ secrets.ORCID_TOKEN }}
        run: |
          python scripts/update_publications.py
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add publications.html
          git diff --cached --quiet || git commit -m "Auto-update publications"
      - name: Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
